name: Created Issues
on: issues

jobs:
  Slack-Notification:
    name: Send GitHub Action trigger data to Slack workflow
    runs-on: ubuntu-latest
    steps:
      - name: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
